### ISSUE TITLE
Update ACM to 2.4

### ISSUE THREAD

**Issue by screeley44** [operate-first/apps#1321]
Should we update ACM to GA'd 2.4? this will also tie into our VolSync as a service idea? VolSync is tech preview in 2.4

see https://github.com/operate-first/support/issues/386 

cc @tumido @HumairAK 

Let me know and I'll submit a PR to update the channel

**Comment by HumairAK** [comment]
@screeley44 sure, we were actually discussing this recently as well. I was thinking next week if another ops member will be available @larsks @4n4nd maybe? 

Anyways we can get the pr going, you can follow this example: https://github.com/operate-first/apps/pull/1001/files

**Comment by larsks** [comment]
I will be around for the first few days next week, but I will be off Thursday and Friday.

**Comment by HumairAK** [comment]
Let's do Monday next week then.

**Comment by screeley44** [comment]
@HumairAK @larsks - PR #1345 ready for Monday

**Comment by HumairAK** [comment]
![image](https://user-images.githubusercontent.com/10904967/142922444-c88d8212-c8e9-4cdb-af2f-b6c8a48f8cc5.png)

<details>
    <summary> status from mch resource </summary> 
    
    ```
      status:
    components:
      application-chart-sub:
        lastTransitionTime: "2021-02-20T15:22:02Z"
        reason: UpgradeSuccessful
        status: "True"
        type: Deployed
      assisted-service-sub:
        lastTransitionTime: "2021-09-16T14:40:56Z"
        reason: UpgradeSuccessful
        status: "True"
        type: Deployed
      cluster-lifecycle-sub:
        lastTransitionTime: "2021-09-16T14:40:56Z"
        reason: UpgradeSuccessful
        status: "True"
        type: Deployed
      cluster-manager-cr:
        lastTransitionTime: "2021-11-22T19:18:37Z"
        message: Components of cluster manager is applied
        reason: ClusterManagerApplied
        status: "True"
        type: Applied
      console-chart-sub:
        lastTransitionTime: "2021-02-20T15:22:02Z"
        reason: UpgradeSuccessful
        status: "True"
        type: Deployed
      discovery-operator-sub:
        lastTransitionTime: "2021-09-16T14:40:55Z"
        reason: UpgradeSuccessful
        status: "True"
        type: Deployed
      grc-sub:
        lastTransitionTime: "2021-02-20T15:22:02Z"
        reason: UpgradeSuccessful
        status: "True"
        type: Deployed
      kui-web-terminal-sub:
        lastTransitionTime: "2021-02-20T15:23:08Z"
        reason: UpgradeSuccessful
        status: "True"
        type: Deployed
      local-cluster:
        lastTransitionTime: "2021-11-22T19:18:37Z"
        message: ManagedCluster is accepted, joined, and available
        reason: ManagedClusterImported
        status: "True"
        type: ManagedClusterImportSuccess
      management-ingress-sub:
        lastTransitionTime: "2021-02-20T15:22:02Z"
        reason: UpgradeSuccessful
        status: "True"
        type: Deployed
      multiclusterhub-repo:
        lastTransitionTime: "2021-10-19T20:40:15Z"
        reason: MinimumReplicasAvailable
        status: "True"
        type: Available
      ocm-controller:
        lastTransitionTime: "2021-10-20T19:45:53Z"
        reason: MinimumReplicasAvailable
        status: "True"
        type: Available
      ocm-proxyserver:
        lastTransitionTime: "2021-10-19T20:39:32Z"
        reason: MinimumReplicasAvailable
        status: "True"
        type: Available
      ocm-webhook:
        lastTransitionTime: "2021-10-19T20:40:14Z"
        reason: MinimumReplicasAvailable
        status: "True"
        type: Available
      policyreport-sub:
        lastTransitionTime: "2021-09-16T14:40:55Z"
        reason: UpgradeSuccessful
        status: "True"
        type: Deployed
      search-prod-sub:
        lastTransitionTime: "2021-02-20T15:23:08Z"
        reason: UpgradeSuccessful
        status: "True"
        type: Deployed
    conditions:
    - lastTransitionTime: "2021-10-19T14:37:07Z"
      lastUpdateTime: "2021-10-19T14:37:07Z"
      message: Failed to deploy CustomResourceDefinition infraenvs.agent-install.openshift.io
      reason: FailedDeployingComponent
      status: "False"
      type: Progressing
    - lastTransitionTime: "2021-11-20T13:42:21Z"
      lastUpdateTime: "2021-11-20T13:42:21Z"
      message: All hub components ready.
      reason: ComponentsAvailable
      status: "True"
      type: Complete
    currentVersion: 2.3.3
    desiredVersion: 2.3.3
    phase: Running

    ```
    

</details>
