### ISSUE TITLE
Pods being evicted in Nodes `oct-03-03-compute` and `oct-03-09-compute` on Smaug cluster

### ISSUE THREAD

**Issue by 4n4nd** [operate-first/apps#1352]
Evicted pod statuses:
```
status:
  phase: Failed
  message: 'Pod The node had condition: [DiskPressure]. '
  reason: Evicted
  startTime: '2021-11-23T14:17:12Z'
```

```
status:
  phase: Failed
  message: >-
    The node was low on resource: ephemeral-storage. Container sparkoperator was
    using 31748Ki, which exceeds its request of 0. 
  reason: Evicted
  startTime: '2021-09-24T18:59:13Z'
```
