### ISSUE TITLE
Investigate and Install Patch Operator to delegate confidential data in non k8s resources to k8s secrets.

### ISSUE THREAD

**Issue by HumairAK** [operate-first/apps#1540]
## Background context
In an ideal world all confidential data on a cluster would be stored within K8S secrets, and then referenced from said secrets. However, this is not always the case. There are different situations where confidential data ends up being added to k8s resources that are _not_ secrets. For instance: 
- OCP Routes holding tls certs
- [Keycloak client CRs](https://github.com/operate-first/apps/blob/master/keycloak/overlays/moc/infra/clients/curator.enc.yaml#L15 ) 

And like the Keycloak client [custom resource](https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/), any new operator could introduce a resource that forces us to put confidential data in their resource directly without the option to pull this information from a secret. This becomes problematic, because GitOps principles encourage us to store as many resources in git as we can.

Currently we solve this by using [sops](https://www.operate-first.cloud/apps/content/argocd-gitops/secret_management.html) to encrypt our files, but this is poor design. Ideally we would only need to encrypt secrets, and leave everything else open and transparent to the public. 

The [Patch operator](https://cloud.redhat.com/blog/enhancing-gitops-with-the-patch-operator) offers a solution, that allows us to reference from any resource field, values that are contained within secrets. The goal of this issue is to try out the Patch Operator in a dev environment, confirm it works, then submit a PR adding this to the Smaug cluster.

## Acceptance criteria
- [ ] Patch Operator tested in dev environmnet, with a resource referencing a value found in a k8s secret, demo'd to another reviewer/approver 
- [ ] Patch Operator subscription added to the apps repo 
- [ ] All keycloak clients referencing their confidential info from a secret, which is patched by the patch operator
- [ ] Accompanying documentation on how to patch a secret using patch operator added to apps repo docs

## Prerequisite knowledge
- Be familiar with [YAML][] syntax
- Know the basics of [kustomize][]
- Know how to work with [git][] and [GitHub][]

[secrets]: https://kubernetes.io/docs/concepts/configuration/secret/
[git]: https://git-scm.com/book/en/v2
[github]: https://github.com/
[kustomize]: https://kustomize.io
[yaml]: https://en.wikipedia.org/wiki/YAML

## Suggestions on how to proceed with this issue
* Get a OCP dev environment, (red hatters can use quicklab) 
* Install patch operator via operate hub 
* Create a patch example where you patch a resource field with a secret value
* As this is a new project, we need to confirm it works as advertised, demo this to another reviewer, report any instabilities/issues/etc.
* Submit a pr adding a subscription to the cluster-scope directory in apps repo, also add it to the smaug overlay kustomization 
* Convert keycloak clients to leverage confidential information from secrets (this will require privileged access, reach out to the ops team for help here)

**Comment by larsks** [comment]
I think that this has a dependency on https://github.com/operate-first/support/issues/298 and on getting the [ExternalSecrets](https://github.com/external-secrets/kubernetes-external-secrets) controller installed (for which I don't think we have an issue yet).

**Comment by dystewart** [comment]
I've installed (via OLM) and tested a few patches using the testing directory at the patch operator github: [https://github.com/redhat-cop/patch-operator](https://github.com/redhat-cop/patch-operator)

So far I have created a testing namespace: `oc new-project test-patch-operator`

Added a serviceaccount to the namespace: `oc create serviceaccount test -n test-patch-operator`

Then added a clusterrole to the default user in the test-patch-operator namespace per the documentation for testing `oc adm policy add-cluster-role-to-user cluster-admin -z default -n test-patch-operator`
I'm not really sure why the cluster-admin role is needed here but this is the explanation they give in their README.md: 
> #shortcut to get all permissions, we are not testing permissions, but the actual patching capability
I should note that without adding a clusterrole here the patch does not work

Next I added the simple_patch.yaml patch:
``` 
apiVersion: redhatcop.redhat.io/v1alpha1
kind: Patch
metadata:
  name: simple-patch
spec:
  patches:
    simple-patch:
      targetObjectRef:
        apiVersion: v1
        kind: ServiceAccount
        name: test
        namespace: test-patch-operator
      patchTemplate: |
        metadata:
          annotations:
            hello: bye
            test3: test3
            test6: test6
      patchType: application/strategic-merge-patch+json
```

And another patch the field_patch.yaml patch:
``` 
apiVersion: redhatcop.redhat.io/v1alpha1
kind: Patch
metadata:
  name: field-patch
spec:
  patches:
    field-patch:
      targetObjectRef:
        apiVersion: v1
        kind: ServiceAccount
        name: test
        namespace: test-patch-operator
      patchTemplate: |
        metadata:
          annotations:
            {{ (index . 1) }}: {{ (index . 2) }}
      patchType: application/strategic-merge-patch+json
      sourceObjectRefs:
      - apiVersion: v1
        kind: Namespace
        name: test-patch-operator
        fieldPath: $.metadata.uid
      - apiVersion: v1
        kind: ServiceAccount
        name: default
        namespace: test-patch-operator
        fieldPath: $.metadata.uid 
```

There are still some features I'm exploring and getting used to but with the field patch it's becoming clear to see that this could be useful for our case.
