### ISSUE TITLE
[workload-overview] Update the project onboarding docs/jupyterbook to include collecting relevant project information

### ISSUE THREAD

**Issue by 4n4nd** [operate-first/apps#1802]
We need to update project onboarding docs/scripts/notebooks to request the following metadata from the users:

```yaml
annotations:
        op1st/project-owner: project-owner-group
        op1st/onboarding-issue: "https://github.com/operate-first/support/issues/MY_ISSUE_NUMBER"
        op1st/docs: "https://www.my-docs.url/"
```
These annotations should be added to the namespace manifests.
