### ISSUE TITLE
Balrog cluster ingress unsecured, certmanager acme challenge refused

### ISSUE THREAD

**Issue by HumairAK** [operate-first/apps#1998]
logs from cert-manager: 

```
E0518 16:54:05.987436       1 sync.go:186] cert-manager/challenges "msg"="propagation check failed" "error"="NS ns-512.awsdns-00.net.:53 returned REFUSED for _acme-challenge.apps.balrog.aws.operate-first.cloud." "dnsName"="apps.balrog.aws.operate-first.cloud" "resource_kind"="Challenge" "resource_name"="ingress-certificate-hk45b-1031415942-3435844338" "resource_namespace"="openshift-ingress" "resource_version"="v1" "type"="DNS-01" 
```

Also noticed balrog certmanager manifests are not being deployed by argocd. 

## Acceptance criteria: 

- [x] fix propagation errors above 
- [ ] deploy custom cert-manager for ocp deployed via aws using dns01 challenge via route53
- [x] add argocd app for balrog cert manager resources (https://github.com/operate-first/apps/issues/1999)

**Comment by HumairAK** [comment]
this is preventing balrog from authenticating against vault due to unsigned cert errors.

**Comment by HumairAK** [comment]
Related issues:

- https://github.com/cert-manager/cert-manager/issues/1933
- https://github.com/cert-manager/cert-manager/issues/3307

I can confirm that setting another dns resolver (e.g. 1.1.1.1) works. But the issue is that this needs to be set as a flag on the deployment, which we can't control because cert-manager is managed by olm. 

The only solution here is to manually deploy cert-manager so we have control over the flags and set: 

- '--dns01-recursive-nameservers=1.1.1.1:53'

Right now I scaled down the cert-manager deployment on balrog, and deployed the following: 

<details>

<summary> cert-manager-deployment.yaml </summary>

```yaml
kind: Deployment
apiVersion: apps/v1
metadata:
  name: cert-manager-custom
  namespace: openshift-operators
  labels:
    app: cert-manager
    app.kubernetes.io/version: v1.8.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: controller
      app.kubernetes.io/instance: cert-manager
      app.kubernetes.io/name: cert-manager
  template:
    metadata:
      labels:
        app: cert-manager
        app.kubernetes.io/component: controller
        app.kubernetes.io/instance: cert-manager
        app.kubernetes.io/name: cert-manager
        app.kubernetes.io/version: v1.8.0
      annotations:
        prometheus.io/port: '9402'
        prometheus.io/path: /metrics
        repository: 'https://github.com/jetstack/cert-manager'
        support: The cert-manager maintainers
        prometheus.io/scrape: 'true'
        containerImage: 'quay.io/jetstack/cert-manager-controller:v1.8.0'
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      serviceAccountName: cert-manager
      securityContext:
        runAsNonRoot: true
      containers:
        - name: cert-manager
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: OPERATOR_CONDITION_NAME
              value: cert-manager.v1.8.0
          securityContext:
            allowPrivilegeEscalation: false
          ports:
            - name: http-metrics
              containerPort: 9402
              protocol: TCP
          imagePullPolicy: IfNotPresent
          image: 'quay.io/jetstack/cert-manager-controller:v1.8.0'
          args:
            - '--v=2'
            - '--cluster-resource-namespace=$(POD_NAMESPACE)'
            - '--leader-election-namespace=kube-system'
            - '--dns01-recursive-nameservers=1.1.1.1:53'
      serviceAccount: cert-manager
  revisionHistoryLimit: 1
```



</details>
