### ISSUE TITLE
Allow the ability to externally access elasticsearch

### ISSUE THREAD

**Issue by HumairAK** [operate-first/apps#229]
For diagnosing/debugging this can be useful, the process is laid out here to do it securely: 

https://docs.openshift.com/container-platform/4.5/logging/config/cluster-logging-log-store.html#cluster-logging-elasticsearch-exposing_cluster-logging-store

**Comment by anishasthana** [comment]
While logging in as the Elasticsearch Service Account is one way to access the contents (you could argue this is a good thing, since it forces you to deliberately log in as the SA), a better way might be to configure searchguard to allow the opf-admins group to have these rights. I also don't see the harm in opening up get access for anyone who has access to the namespace. I haven't used the logging operator before so I don't know what flags you'd be tweaking, but it's definitely possible to set permissions for interacting with the ES api.

**Comment by HumairAK** [comment]
> a better way might be to configure searchguard to allow the opf-admins group to have these rights 

Yes I imagine we'll have to do something along these lines.  We probably will need to be able allow other users to use their ocp tokens as bearer tokens to query elasticsearch api endpoint.

**Comment by drbwa** [comment]
> We probably will need to be able allow other users to use their ocp tokens as bearer tokens to query elasticsearch api endpoint.

Exactly. There are probably use cases where a user might want to retrieve logs programmatically (i.e. from ES). To feed logs into their own alerting and anomaly detection logic, to try and determine whether an issue is likely to be due to a fault in their own system or rather due to a dependency. I don't know to what extent all logs can be made available to all users. For our specific use case, the more logs of different components we have access to, the better the coverage or ability to detect issues of our tool is going to be.

**Comment by HumairAK** [comment]
Okay so I went down the rabbithole that is opendistro for elasticsearch (which is what it seems like CLO uses). Will share my findings here: 

- Elasticsearch that is provisioned by ES operator (provisioned by CLO) has an [oauth proxy](https://github.com/openshift/elasticsearch-proxy) infront of it
- The proxy is configured in such a way that it will assign the `x-forwarded-roles` header one of 2 roles, they are: 
    - admin_reader : this is assigned if the user accessing the endpoint has the following access: `{"namespace": "default", "verb":
          "get", "resource": "pods/log"}` 
    - project_user : applied by default if `admin_reader` is not applicable to this user
- The configuration for what permissions these roles have are found in `config.yml` under `/opt/app-root/src/sgconfig`. From what I understand opendistro provides a script to move these permissions from `sgconfig` to the `.security` index, once having done so -- the permissions take affect. 
- The current permissions for `admin_reader` are (found in `/opt/app-root/src/sgconfig/roles.yml` on the es nodes): 

```
project_user:
  readonly: true
  cluster:
    - CLUSTER_COMPOSITE_OPS_RO
    - MONITOR
    - indices:data/write/bulk  #required for being able to let index mappings update... is this required still with multitenancy?
  indices:
    app:
      '*':
        - READ
      _dls_: '{"bool":{"filter":{"terms":{"kubernetes.namespace_name":[${attr.proxy.ns}]}}}}'
    '?kibana_*_${user_name}':
      '*':
        - CRUD

admin_user:
  readonly: true
  cluster:
    - CLUSTER_MONITOR
    - CLUSTER_COMPOSITE_OPS_RO
    - indices:data/write/bulk  #required for being able to let index mappings update... is this required still with multitenancy?
  indices:
    '*':
      '*':
        - READ
        - INDICES_MONITOR
    '?kibana_*':
      '*':
        - CRUD
  tenants:
    admin: RW
```

- There is no obvious way I've seen to specify these roles in the clusterlogging CR based on the docs, and adding more roles based on rbac access would probably require making changes to the proxy container flags. 
- We may be able to use Kibana to add users, this seems possible based on the open distro docs [here](https://opendistro.github.io/for-elasticsearch-docs/docs/security/access-control/users-roles/#kibana)
- There's also adding users via the rest api [here](https://opendistro.github.io/for-elasticsearch-docs/docs/security/access-control/users-roles/#rest-api).
- Based on the search guard configs, the 2nd method of authentication is done via certs as [described here](https://docs.search-guard.com/latest/client-certificate-auth) 

The easiest / fastest way right now seems like to just give those that are blocked the rbac access to pods/logs in `default` namespace, but this _is_ a cluster admin ns, though it doesn't have any pods. The next method that would be to either use kibana or rest api, though this would mean we can't store these as neatly declaratively. I don't yet have a neat solution whereby we store everyone's active permissions in ES neatly in git.
