### ISSUE TITLE
ODH 1.0 upgrade path

### ISSUE THREAD

**Issue by tumido** [operate-first/apps#231]
Upgrade ODH components to 1.0.0 release

- [x] Operator upgrade - automated approval, already updated (cleanup was needed https://github.com/operate-first/apps/pull/234)
- [x] Argo (https://github.com/operate-first/apps/pull/233)
- [x] Dashboard (https://github.com/operate-first/odh-dashboard/issues/7, https://github.com/operate-first/odh-dashboard/pull/8)
- [x] Data catalog (https://github.com/operate-first/apps/pull/236)
- [x] Jupyterhub (https://github.com/operate-first/apps/pull/238)
- [x] Kafka (https://github.com/operate-first/apps/pull/235)
- [x] Monitoring (https://github.com/operate-first/apps/pull/239)
- [x] Superset (https://github.com/operate-first/apps/pull/237)

**Comment by HumairAK** [comment]
For reference these are the patch notes: 

 - Update JupyterHub image to 0.1.5
 - Update Argo to v2.12.5
 - Add Thriftserver to data catalog
 - Add Hue to data catalog
 - Kafka dashboard: migrate singlestat to new stat panel
From [here](https://github.com/opendatahub-io/odh-manifests/releases)

**Comment by tumido** [comment]
>  - Update Argo to v2.12.5
> - Add Thriftserver to data catalog
> - Add Hue to data catalog

We already used those from ODH `master`, so the only changes that applies to us are basically:

- Update JupyterHub image to 0.1.5
- Kafka dashboard: migrate singlestat to new stat panel

**Comment by HumairAK** [comment]
Kafka kfdef updated

**Comment by HumairAK** [comment]
Data catalog kfdef updated

**Comment by HumairAK** [comment]
Argo kfdef Updated

**Comment by HumairAK** [comment]
Superset kfdef updated: 

```
time="2021-02-10T14:10:56Z" level=info msg="Successfully applied application superset"
```

**Comment by tumido** [comment]
Superset `DeploymentConfig`'s rollout is unable to complete due to PVC `readWriteOnce` (while the previous replica is trying to access it still)

![image](https://user-images.githubusercontent.com/7453394/107521254-9c908600-6bb2-11eb-9200-838598415d97.png)

**Comment by HumairAK** [comment]
Killing old pods

**Comment by anishasthana** [comment]
As an additional note, you may need to add  `jupyterhub_config.py: c.OpenShiftOAuthenticator.validate_cert = False ` to your jupyterhub-configmap when you upgrade, depending on the MOC cert situation.

**Comment by HumairAK** [comment]
thanks @anishasthana

**Comment by HumairAK** [comment]
Superset looks good

**Comment by tumido** [comment]
Superset migration bug reported upstream: https://github.com/opendatahub-io/odh-manifests/issues/308

**Comment by tumido** [comment]
ODH Dashboard fork image rebuilt, pushed and deployed. Looks good.

**Comment by 4n4nd** [comment]
Monitoring was updated

**Comment by HumairAK** [comment]
For monitoring we noticed that  `jupyterhub-metrics` service monitor was not automatically cleaned up (it was removed in 1.0.0), and had to be manually removed.

**Comment by tumido** [comment]
Service monitor not deleting reported upstream: https://github.com/opendatahub-io/odh-manifests/issues/309

**Comment by HumairAK** [comment]
Updating JH

**Comment by HumairAK** [comment]
JH kfdef updated, verifying changes.

**Comment by tumido** [comment]
JH deployment config is missing `ImageChange` trigger

**Comment by HumairAK** [comment]
```---> Running application from script (/opt/app-root/builder/run) ...
+ trap 'kill -TERM $PID' TERM INT
+ PID=36
+ wait 36
+ start-jupyterhub.sh
+ set -eo pipefail
+ PATH=/opt/app-root/bin:/opt/rh/rh-python36/root/usr/bin:/opt/rh/rh-nodejs10/root/usr/bin:/opt/rh/httpd24/root/usr/bin:/opt/rh/httpd24/root/usr/sbin:/opt/app-root/src/.local/bin/:/opt/app-root/src/bin:/opt/app-root/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/app-root/scripts
+ . /opt/app-root/etc/jupyterhub_config.sh
++ '[' x '!=' x ']'
++ '[' -f /opt/app-root/src/.jupyter/jupyterhub_config.sh ']'
++ '[' -f /opt/app-root/configs/jupyterhub_config.sh ']'
+ exec jupyterhub -f /opt/app-root/etc/jupyterhub_config.py
[I 2021-02-10 14:52:32.201 JupyterHub app:2349] Running JupyterHub version 1.3.0
[I 2021-02-10 14:52:32.202 JupyterHub app:2380] Using Authenticator: oauthenticator.openshift.OpenShiftOAuthenticator-0.12.4dev
[I 2021-02-10 14:52:32.202 JupyterHub app:2380] Using Spawner: builtins.OpenShiftSpawner
[I 2021-02-10 14:52:32.202 JupyterHub app:2380] Using Proxy: jupyterhub.proxy.ConfigurableHTTPProxy-1.3.0
[D 2021-02-10 14:52:32.204 JupyterHub app:2312] Could not load pycurl: No module named 'pycurl'
    pycurl is recommended if you have a large number of users.
[D 2021-02-10 14:52:32.205 JupyterHub app:1460] Generating new cookie_secret
[I 2021-02-10 14:52:32.205 JupyterHub app:1465] Writing cookie_secret to /opt/app-root/data/cookie_secret
[D 2021-02-10 14:52:32.206 JupyterHub app:1587] Connecting to db: postgresql://jupyterhub:[redacted]@jupyterhub-db:5432/jupyterhub
[D 2021-02-10 14:52:32.256 JupyterHub application:653] Exiting application: jupyterhub
Found database schema version 896818069c98 != 4dc2d5a8c53c. Backup your database and run `jupyterhub upgrade-db` to upgrade to the latest schema.
+ trap - TERM INT
+ wait 36
+ STATUS=1
+ exit 1

```

**Comment by HumairAK** [comment]
Cloning pvc in order to run db upgrade

**Comment by tumido** [comment]
Reported: https://github.com/opendatahub-io/odh-manifests/issues/311

**Comment by HumairAK** [comment]
So we don't have CSI driver support for easy cloning: 
```
failed to provision volume with StorageClass "ocs-storagecluster-cephfs": CSI driver does not support clone operations: controller CLONE_VOLUME capability is not reported
```

Backed up data locally instead
`oc -n opf-jupyterhub rsync  jupyterhub-db-2-5ww2w:/var/lib/pgsql/data backup/ > backup/output.txt`

**Comment by tumido** [comment]
We're gonna apply a migration job

```yaml
kind: Job
apiVersion: v1
metadata:
  name: jupyterhub-migrate
  namespace: opf-jupyterhub
spec:
  serviceAccountName: jupyterhub-hub
  containers:
    - resources:
        limits:
          memory: 1Gi
        requests:
          memory: 1Gi
      name: jupyterhub-migrate
      env:
        - name: JUPYTERHUB_SERVICE_NAME
          value: jupyterhub
        - name: JUPYTERHUB_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: jupyterhub
              key: POSTGRESQL_PASSWORD
        - name: JUPYTERHUB_DATABASE_HOST
          value: jupyterhub-db
      imagePullPolicy: Always
      image: jupyterhub-img:latest
      command: ["jupyterhub", "upgrade-db"]

```
