### ISSUE TITLE
Add proxy for Prometheus  instances

### ISSUE THREAD

**Issue by 4n4nd** [operate-first/apps#24]
Add a proxy to the prometheus instance so that only authenticated users have access to it.

This can be done by adding a proxy container to the Prometheus config:
```yaml
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: odh-monitoring
  labels:
    app: prometheus
    prometheus: k8s
spec:
  serviceMonitorSelector: {}
  securityContext: {}
  ruleSelector: {}
  replicas: 2
  containers:
  - name: oauth-proxy
    image: openshift/oauth-proxy:latest
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 8443
      name: public
    args:
    - --https-address=:8443
    - --provider=openshift
    - --openshift-service-account=proxy
    - --upstream=http://localhost:9090
    - --tls-cert=/etc/tls/private/tls.crt
    - --tls-key=/etc/tls/private/tls.key
    - --cookie-secret=SECRET
```
