### ISSUE TITLE
Op1st Which namespaces can and cannot be decomissioned

### ISSUE THREAD

**Issue by Gregory-Pereira** [operate-first/apps#2782]
what follows is a list of from which projects things can be removed.
```
OSC Clusters No longer under op1st management, no cleanup required.
Infra:
  Keeping:
    - argocd
    - acm
    - acm-issuer
    - argocd-managed-broker
    - external-secrets-operator
    - default
    - idp-auth-primary
    - idp-mgmt-config
    - idp-mgmt-dex
    - idp-mgmt-operate-first
    - jerry
    - local-cluster
    - openshift*
    - open-cluster-management*
    - ocp-prod
    - ocp-staging
    - service-catalog-k8s-plugin
    - smaug
    - vault
    - web-terminal-service-catalog
  Removing workloads from:
    - acme-operator
    - anonymous
    - balrog (HAS TO BE FORCED, STUCK DELETING)
    - curator
    - default-broker
    - drvbw-broker
    - fio-benchmarking
    - ggithubcom-harshad16-summit-2021-octo-keynote-ns
    - ggithubcom-ipolonsk-application-samples-ns
    - ggithubcom-larsks-example-k8s-app-ns
    - ggithubcom-oglok-edge-app-ns
    - ggithubcom-open-cluster-management-application-samples-ns
    - ggithubcom-redhat-et-scribe-poc-ns
    - hive
    - ilana-aws
    - ilanaws
    - kcp-pipeline
    - kubeflow-aws-test-cluster
    - lars-sandbox
    - multicluster-engine
    - nsgithubcom-aicoe-summit-2021-octo-keynote-ns
    - nsgithubcom-cooktheryan-summit-2021-octo-keynote-ns
    - nsgithubcom-ipolonsk-application-samples-ns
    - octo-ushift-dev-broker
    - opf-alertreceiver
    - opf-monitoring
    - rick 
    - storage-benchmarking
    - summit-2021-octo-keynote
    - verify
Smaug
  Keeping:
    - assisted-installer (not sure about this, seems specific to openshift on baremetal)
    - default
    - dex 
    - external-secrets
    - external-secrets-operator
    - janus-idp
    - open-cluster-management* (acm observability)
    - openshift*
    - opf-argo
    - opf-ci-pipelines
    - opf-ci-prow
    - opf-ci-test-pods
    - peribolos-as-a-service
    - reloader
    - service-catalog
    - service-catalog-k8s-plugin
    - smaug
    - vault
    - web-terminal-service-catalog
  Removing:
    - acme-operator
    - ai-services-thanos-grpc
    - ai4cloudops
    - aicoe-meteor
    - aiops-tools-workshop
    - anonymous
    - api-designer
    - apicurio-apicurio
    - b4mad-minecraft
    - b4mad-racing
    - banzaicloud-vault
    - bragi
    - bu-cs-book-dev
    - bu-scsaol
    - caas
    - copilot-ops
    - curator-operator-system
    - debezium-ui
    - demolab
    - demolab-dev
    - demolab-staging
    - ds-github-labeler
    - ds-ml-workflows-ws
    - fedora
    - fio-benchmarking
    - gingersnap
    - highlander
    - humair-sandbox
    - kaoto
    - koku-metrics-operator
    - kubeflow
    - kubesmarts
    - jet-linite
    - kvm-device-plugin
    - lars-sandbox
    - lotus
    - manageiq
    - neu-cs6620
    - nfs-server-and-provisioner
    - node-labeler
    - od-demo
    - okd-centos
    - okd-team
    - okd-wg
    - opendatahub-operator
    - opentelemetry-collector-operator
    - opf-alertreceiver
    - opf-dashboard
    - opf-google-spark-operator
    - opf-grafana-public
    - opf-jupyterhub
    - opf-jupyterhub-stage
    - opf-kafka
    - opf-monitoring
    - opf-observatorium
    - opf-pulp
    - opf-seldon
    - opf-slack-first
    - opf-superset
    - opf-triage-party
    - opf-trino
    - opf-trino-stage
    - ops-testing
    - prometheus-ai-project
    - rapidast
    - ray-bu
    - report-system
    - rh-curator-eval
    - robozome
    - sigstore-aas
    - smart-village-view
    - storage-benchmarking
    - tekton-chains 
    - tekton-pipelines (not sure about this one if janus uses anything tekton related)
    - test
    - thoth-amun-api-prod
    - thoth-amun-inspection-prod
    - thoth-backend-prod
    - thoth-bots-prod
    - thoth-cre-integration
    - thoth-deployment-examples
    - thoth-frontend-prod
    - thoth-graph-prod
    - thoth-infra-prod
    - thoth-middletier-prod
    - tremor-demo
    - wildfly-service
Jerry
  Keeping nothing, removing everything, can't hit any endpoint on the cluster, not certain it still exists 
Curator:
  Keeping nothing, removing everything, cant even authenticate to cluster, stuck in a oauth callback loop

Not sure about OCP-PROD and OCP-STAGING
```
 Would appreciate a thorough look from @tumido to ensure im not removing workloads required by Janus, or that I have spared things which can be removed.
 /cc @cooktheryan
