### ISSUE TITLE
Run Ceph on Quicklab

### ISSUE THREAD

**Issue by martinpovolny** [operate-first/apps#279]
I am trying to get Ceph running on quicklab. I have created an Argo App pointing to our repo:

https://argocd-server-aicoe-argocd-dev.apps.mpovtest.lab.upshift.rdu2.redhat.com/applications/ceph?operation=true

I get this error message:

"the server could not find the requested resource"

Seems OCS is not on the cluster. I need to install it? https://github.com/openshift/ocs-operator ?

FYI @HumairAK, @tumido

**Comment by martinpovolny** [comment]
So the next step is to re-create the cluster (is has some issue) and then install the OCS operator and retry.

**Comment by HumairAK** [comment]
Yeah the resource being installed is: 
```
apiVersion: ocs.openshift.io/v1
kind: StorageCluster
metadata:
  name: ocs-storagecluster
  namespace: openshift-storage
```

Which comes from the CRDs instroduced by ocs, so you'd need that operator installed. I don't know too much about ocs unfortunately and/or how it would cooperate with quicklab environments, but if you get it working, let us know!
