### ISSUE TITLE
Add Storage to Kafka deployment

### ISSUE THREAD

**Issue by 4n4nd** [operate-first/apps#467]
We need to add PVCs to the kafka deployment, rn all messages are ephemeral so in case of pod restarts all messages get deleted.

**Comment by 4n4nd** [comment]
Closed by https://github.com/operate-first/apps/pull/465

**Comment by 4n4nd** [comment]
The Configuration was updated but kafka needs to be recreated for the PVC changes to take effect:
```yaml
status:
  conditions:
    - lastTransitionTime: '2021-03-31T19:42:51.455840Z'
      message: >-
        The desired ZooKeeper storage configuration contains changes which are
        not allowed. As a result, all storage changes will be ignored. Use DEBUG
        level logging for more information about the detected changes.
      reason: ZooKeeperStorage
      status: 'True'
      type: Warning
    - lastTransitionTime: '2021-03-31T19:42:51.451015Z'
      message: >-
        The desired Kafka storage configuration contains changes which are not
        allowed. As a result, all storage changes will be ignored. Use DEBUG
        level logging for more information about the detected changes.
      reason: KafkaStorage
      status: 'True'
      type: Warning
```
