### ISSUE TITLE
Add Vector deployment manifests to git

### ISSUE THREAD

**Issue by HumairAK** [operate-first/apps#495]
Currently a manual manifests exists within the `opf-kafka` namespace for vector. This was done for test purposes. The next action items need to be: 

- [ ] Clean up the lingering deployments not tracked in git 
- [ ]  Add vector manifests as a new vector app in the `operate-first/apps` repo, make a re-usable generic base, then add the observatorium overlay, and structure it so we can add multi namespace deployments easily by pulling from base. 
- [ ]  Add argocd-app for this deployment, and deploy it via argocd.

**Comment by 4n4nd** [comment]
@tumido @HumairAK did we agree that we want to deploy it alongside observatorium?

This is what a vector config looks like
```yaml
---
sources:
  opf_kafka_source:
    type: kafka
    bootstrap_servers: odh-message-bus-kafka-bootstrap.opf-kafka.svc:9092
    group_id: cluster-logs-consumer
    key_field: message_key
    topics:
    - zero-prod.cluster.app-logs
sinks:
  opf_loki_sink:
    type: loki
    inputs:
    - opf_kafka_source
    endpoint: http://opf-observatorium-loki-distributor-http.opf-observatorium.svc:3100
    tenant_id: cluster-app-logs
    encoding:
      codec: text
      only_fields:
        - message
    healthcheck:
      enabled: true
    labels:
      forwarder: vector
```
