### ISSUE TITLE
Test out giving a single prom instance rbac to multi namespaces 

### ISSUE THREAD

**Issue by HumairAK** [operate-first/apps#57]
Since the odh-dashboard requires a single component instance installed via kfdef to pick up it's route, it would be ideal if we could have only one odh deployed prometheus instance via one odh deployed prometheus operator. 

This issue is to test out if we can have service/pod monitors all deployed in a single namespace like `opf-monitoring` then give rbac to a single prometheus instance to other namespaces like `opf-jupyterhub` and `opf-argo` and monitor them from a single source.

**Comment by 4n4nd** [comment]
Test results:
1. When the servicemonitors are in the same namespace as prometheus, with the namespace for the target service specified, the prometheus SA just needs to be able to `get/list/watch services`  from the target namespace and it is able to monitor services across namespaces.

2. When the servicemonitors are not in the same namespace as prometheus, then the prometheus needs to be able to `get namespaces` (cluster role) as well as `get/list/watch servicemonitors/podmonitors/services/pods/endpoints` in the target namespaces.
If we apply this role cluster wide, it would look like:
```yaml

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operatefirst-monitoring-cluster
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - services
  - endpoints
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  - podmonitors
  verbs:
  - get
  - list
  - watch
```
Method 2 would also fix #60, i.e. we would have permissions to access cluster metrics enabling better monitoring for our pods/deployments.

**Comment by tumido** [comment]
So in other words... we found the solution! :slightly_smiling_face: Do I understand it correctly? :tada:  I like the method 2, since it keeps the monitors and services it monitors together.

Does the method 2 also work without a cluster role? I mean, if you use a `Role` and `RoleBinding` in each target namespace giving access to the prometheus SA from the monitoring namespace.

**Comment by 4n4nd** [comment]
> So in other words... we found the solution! :slightly_smiling_face: Do I understand it correctly? :tada:  I like the method 2, since it keeps the monitors and services it monitors together.
> 
> 
> 
> Does the method 2 also work without a cluster role? I mean, if you use a `Role` and `RoleBinding` in each target namespace giving access to the prometheus SA from the monitoring namespace.

We will need at least one cluster role that will let the Prometheus do a `get` on namespaces.

**Comment by tumido** [comment]
why? You can do a role for `get` on the target namespaces only. But I agree that a single cluster role, may be simpler to maintain.

**Comment by tumido** [comment]
BTW... It just came to my mind... If we use which cluster role. The prometheus would scape all the *monitors in the cluster, wouldn't it? Like .. it there's somebody else deploying a service monitor in some non-operate-first namespace, we would still scrape that, in case we use the cluster role. I don't think we want that. I would rather try the `Role`s scenario if possible.

**Comment by 4n4nd** [comment]
> You can do a role for get on the target namespaces only

I don't think you can. To do something like a `oc get namespace -l key=value` you need `get` access on namespaces clusterwide.

> we would still scrape that

if set our selector labels properly, that should not be an issue, we can define a label `prometheus: operate-first` for all our service monitors and it should be fine.

**Comment by HumairAK** [comment]
Awesome work @4n4nd, so correct me if I'm wrong but it boils down to this: 

Option 1: 
- We can have service monitors same namespace
Pro: 
- no cluster rbac
Con: 
- We need to create the service monitors, ns owners need to create NS scoped rbac 

Option 2: 
- We can put service monitors in different namespaces
Pro: 
- Service monitors can go with different namespaces, resulting in shifting onus to enable monitoring to namespace admins (less work for us in the future) 
Con: 
- Need cluster rbac 


Personally I think we should go with option 1. I feel like giving a service cluster wide access to cluster resources is not good practice.

**Comment by anishasthana** [comment]
++ what Humair said. I think removing the need for cluster-wide perms where possible makes it easier for people to use the operate-first setup

**Comment by tumido** [comment]
hold on, give me a sec to write down the POC, before we decide...

**Comment by tumido** [comment]
So.. it seems the `namespace` resource needs the cluster scope, however `project` resources don't:

```
$ oc new-project test1
Now using project "test1" on server "https://api.tcoufaltest.lab.pnq2.cee.redhat.com:6443".
...

$ oc new-project test2
Now using project "test2" on server "https://api.tcoufaltest.lab.pnq2.cee.redhat.com:6443".
...

$ oc new-project test3
Now using project "test3" on server "https://api.tcoufaltest.lab.pnq2.cee.redhat.com:6443".
...

$ oc create serviceaccount -n test1 test-sa
serviceaccount/test-sa created

$ oc apply -f rbac.yaml -n test1
role.rbac.authorization.k8s.io/test-role created
rolebinding.rbac.authorization.k8s.io/test-rb created

$ oc apply -f rbac.yaml -n test2
role.rbac.authorization.k8s.io/test-role created
rolebinding.rbac.authorization.k8s.io/test-rb created

$ oc apply -f rbac.yaml -n test3
role.rbac.authorization.k8s.io/test-role created
rolebinding.rbac.authorization.k8s.io/test-rb created

$ oc login --token=TEST_SA_TOKEN

$ oc get namespaces
Error from server (Forbidden): namespaces is forbidden: User "system:serviceaccount:test1:test-sa" cannot list resource "namespaces" in API group "" at the cluster scope

$ oc get projects
NAME    DISPLAY NAME   STATUS
test1                  Active
test2                  Active
test3                  Active
```

Using this `rbac.yaml`:
```yaml
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: test-role
rules:
  - apiGroups:
      - project.openshift.io
    resources:
      - projects
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
      - list
      - watch
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: test-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: test-role
subjects:
  - kind: ServiceAccount
    name: test-sa
    namespace: test1
```

@4n4nd this is basically the exercise I wanted you to prove. Please try out things first next time. The question is. Do we need to be able list `namespaces`? Or are `project` resources fine? Do you know how the prometheus operator approaches this? What does it need? Namespaces or projects?

To conclude on this from my point of view. I don't like cluster roles in this case and working around them in by labels and what not, seems like a bad idea to me. If we can't use this option 3 - with scoping the namespace/project access as shown above, I would choose number 1, We don't want to play this on cluster scope - that would effectively equal cluster wide Prometheus deployment anyways (which we don't want now).
