### ISSUE TITLE
[Automation] Script for automating Onboarding to Cluster 

### ISSUE THREAD

**Issue by HumairAK** [operate-first/apps#635]
The steps [here](https://www.operate-first.cloud/users/support/docs/onboarding_to_cluster.md) should be automated within a script. Either we can extend the current [onboarding script](https://github.com/operate-first/apps/blob/master/scripts/onboarding.sh) used as one of the steps to handle the whole procedure, or create a new one. The tricky part would be handling pgp keys. 

I'm imagining the usage would look something like this: 

```
$ ./onboard_to_cluster.sh [team_name] [list_of_namespaces] [list_of_users] [project_description] [env] [cluster] -o <optional_pgp_key>
```

Maybe it would be better to require a yaml file with a set schema like: 

```yaml
onboarding_template:
  team-name: example_team
  list-of-namespaces:
    - ns_1
    - ns_2
  list-of-users:
    - user_1
    - user_2
  project_description: "example description" 
  env: MOC
  cluster: ZERO
  optional_pgp_keys:
    - key_1
    - key_2
```

And the script can just consume this file: 

```bash
$ ./onboard_to_cluster.sh onboard.yaml
```

Then a next step can be to eventually have people fill out a yaml/form and have a bot perform the PR.
