### ISSUE TITLE
re-scale Loki microservice deployments

### ISSUE THREAD

**Issue by 4n4nd** [operate-first/apps#847]
Loki microservices like Loki-Distributor and Loki-Ingester are very network intensive components and not cpu/memory consuming. So we can get by with give them lower amounts of cpu/memory and increasing the number of replicas  for each component.

**Comment by 4n4nd** [comment]
updated resources to the following for Loki Distributor and Loki Ingester services:
```yaml
- resources:
        requests:
          cpu: 300m
          memory: 300Mi
```
Also scaled both of them up to `5` replicas each
